name: K8s Workflow
on:
  push:
    branches:
      - mast
jobs:
  deploy-cluster:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Terraform
      run: |
        TERRAFORM_VERSION="1.0.9"
        wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
        unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
        terraform --version

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        project_id: encoded-stage-408805
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Initialize Terraform for Cluster
      run: |
        cd Terraform
        terraform init

    - name: Apply Terraform Configuration for Cluster
      run: |
        cd Terraform
        kubectl get nodes
        # terraform apply -auto-approve
    - name: Deploy Nginx Application
      run: |
        kubectl apply -f nginx.yaml

    - name: Wait for LoadBalancer IP
      run: |
        sleep 30  # Adjust this sleep duration based on your cluster's provisioning time
        kubectl get svc nginx-deployment -o jsonpath='{.status.loadBalancer.ingress[0].ip}' | tee nginx-ip.txt
    - name: Check if App is Hosted
      run: |
        EXTERNAL_IP=$(cat nginx-ip.txt)
        STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://$EXTERNAL_IP)

        if [ $STATUS_CODE -eq 200 ]; then
          echo "Application is hosted and accessible. HTTP Status Code: $STATUS_CODE"
        else
          echo "Application may not be accessible. HTTP Status Code: $STATUS_CODE"
          exit 1
        fi
  destroy-cluster:
    runs-on: ubuntu-latest

    needs: deploy-cluster

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Terraform
      run: |
        TERRAFORM_VERSION="1.0.9"
        wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
        unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
        terraform --version

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        project_id: encoded-stage-408805
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Destroy Terraform Resources for Cluster
      run: |
        cd Terraform
        terraform destroy -auto-approve
  # deploy-application:
  #   runs-on: ubuntu-latest

  #   needs: deploy-cluster

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2

  #   - name: Install Terraform
  #     run: |
  #       TERRAFORM_VERSION="1.0.9"
  #       wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
  #       unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
  #       sudo mv terraform /usr/local/bin/
  #       terraform --version

  #   - name: Setup Google Cloud CLI
  #     uses: google-github-actions/setup-gcloud@v0.3.0
  #     with:
  #       project_id: kube
  #       service_account_key: ${{ secrets.GCP_SA_KEY }}
  #       export_default_credentials: true

  #   - name: Initialize Terraform for Application
  #     run: |
  #       cd path/to/terraform/application
  #       terraform init

  #   - name: Apply Terraform Configuration for Application
  #     run: |
  #       cd path/to/terraform/application
  #       terraform apply -auto-approve

  # delete-cluster:
  #   runs-on: ubuntu-latest

  #   needs: deploy-application

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2

  #   - name: Install Terraform
  #     run: |
  #       TERRAFORM_VERSION="1.0.9"
  #       wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
  #       unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
  #       sudo mv terraform /usr/local/bin/
  #       terraform --version

  #   - name: Setup Google Cloud CLI
  #     uses: google-github-actions/setup-gcloud@v0.3.0
  #     with:
  #       project_id: kube
  #       service_account_key: ${{ secrets.GCP_SA_KEY }}
  #       export_default_credentials: true

  #   - name: Initialize Terraform for Cluster Deletion
  #     run: |
  #       cd path/to/terraform/cluster
  #       terraform init

  
